create a way to add some additional params to redirect url
badgateway/oauth2-client pull request #116
Opened 2023-07-28 13:24 UTC by pks1989

Hi! I very like you library for lightweight. But custom auth server in my company wants to have some specific user info form redirect URL. Like deviceId, analytics systems id and other. And i don't see possibility do that with this lib.

2023-07-29 17:32 UTC, evert requested changes
Unittests would also be very welcome for this. It will make it easier for me to quickly merge and publish.

2023-07-29 17:32 UTC, evert commented on src/client/authorization-code.ts
> +  async getAuthorizeUri(params: GetAuthorizeUrlParams, customParams?: GetAuthorizeUrlCustomParams): Promise<string> {
The need for this makes sense. `clientCredentials` also has some support for this, but there they are called `extraParams`. Could you take a look here:

https://github.com/badgateway/oauth2-client/blob/main/src/client.ts#L135

And make the naming convention and type structure identical to what is done here? Also, there's some security measures there that are important here too. We don't want users to accidentally overwrite parameters.

Here's the pull request that introduced that feature:

https://github.com/badgateway/oauth2-client/pull/91

2023-07-31 12:54 UTC, pks1989 commented on src/client/authorization-code.ts
> +  async getAuthorizeUri(params: GetAuthorizeUrlParams, customParams?: GetAuthorizeUrlCustomParams): Promise<string> {
@evert Hi. Thanks you for review. I change naming and type structure. Аdd "core params" rewrite checking. 
Also add unit test for positive and negative cases of uses extraParams.

2023-08-03 02:37 UTC, evert commented on src/client/authorization-code.ts
> +   * List of non-standard parameters that may need, if your auth server want to have some additional info in url
```suggestion
   * Any parameters listed here will be added to the query string for the authorization server endpoint.
```

2023-08-03 02:38 UTC, evert commented
Looks good! just some lint errors now

2023-08-07 12:58 UTC, pks1989 commented
> Looks good! just some lint errors now

Fixed :) All green now

2023-08-09 20:11 UTC, merged

2023-09-05 21:48 UTC, motnyk commented
👋 @evert, just checking if you have any plans to release a 2.2.4 version of the client with this change anytime soon?

2023-09-05 21:49 UTC, evert commented
Lets do it!

2023-09-05 21:59 UTC, evert commented
Done